name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

     - name: Instalar Dependências
  run: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest  # Garante que pytest está instalado

- name: Executar Testes Unitários
  run: pytest

