name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest bandit

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Executar Testes Unitários
        run: pytest tests/

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install --upgrade pip
          pip install bandit

      - name: Análise Estática de Código com Bandit
        run: bandit -r . -ll

  dast:
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: Iniciar Aplicação em Container
        run: |
          if [ -f "docker-compose.yml" ]; then
            docker-compose up -d
          else
            echo "Erro: Arquivo docker-compose.yml não encontrado!"
            exit 1
          fi

      - name: Aguardar Aplicação Inicializar
        run: sleep 30

      - name: Executar OWASP ZAP Scan
        run: |
          docker run --network="host" -v $(pwd):/zap/wrk -t owasp/zap2docker-stable zap-baseline.py \
          -t http://localhost:8080 -r zap-report.html

      - name: Upload do Relatório ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap-report.html

  deploy:
    runs-on: ubuntu-latest
    needs: dast

    steps:
      - name: Deploy para Staging
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploy para Staging..."
          # Comandos de deploy para staging aqui

      - name: Aprovação para Produção
        if: github.ref == 'refs/heads/main'
        uses: hmarr/auto-approve-action@v3

      - name: Deploy para Produção
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploy para Produção..."
          # Comandos de deploy para produção aqui

  monitoring:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Instalar Prometheus e Node Exporter
        run: |
          docker run -d --name prometheus -p 9090:9090 prom/prometheus
          docker run -d --name node-exporter -p 9100:9100 prom/node-exporter

      - name: Configurar Alertas com Prometheus
        run: |
          echo "Configurando alertas de segurança..."
          # Adicionar regras de alerta para detecção de anomalias

      - name: Instalar e Configurar Fail2Ban
        run: |
          sudo apt update && sudo apt install -y fail2ban
          sudo systemctl enable fail2ban && sudo systemctl start fail2ban

      - name: Monitorar Logs de Segurança
        run: |
          tail -f /var/log/auth.log &

      - name: Enviar Alertas de Segurança
        run: |
          echo "Monitoramento ativo. Enviando alertas para tentativas de ataque..."
          # Configuração de notificações (exemplo: Slack, Email, PagerDuty)
